apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: {{ .Values.app}}
  ports:
    port: {{ .Values.service.port}}
    protocol: {{ .Values.service.protocol}}
    targetPort: {{ .Values.service.targerport}}
  type: {{ .Values.service.type}}
