kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values-staging.yml
    path: project/helm
    repoURL: https://github.com/rao-naveen/nd064_course_1
    targetRevision: HEAD
