namespace: sandbox
name: techtrends
app: techtrends
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
image:
  repository: techtrends
  tag: latest
  pullpolicy: IfNotPresent

dockerusername: jnaveenrao
replicaCount: 1
resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
containerPort: 3111
livenessProbe:
              path: /healthz
              port: 3111
readinessProbe:   
              path: /healthz
              port: 3111
